yadis_discovery.go
@yohcop pls review
* Make X-XRDS-Location Header Case-Insensitive
As [python-openid](https://github.com/openid/python-openid) support case-insensitive  ``X-XRDS-Location`` header and even use it in it's [Example](https://github.com/openid/python-openid/blob/f7e13536f0d1828d3cef5ae7a7b55cabadff37fc/examples/djopenid/templates/server/index.html#L30). Support case-insensitive ``X-XRDS-Location`` header make openid-go works well with these legacy implements.
=> Make X-XRDS-Location Header Case-Insensitive

nonce_store.go, nonce_store_test.go
Currently `SimpleNonceStore` only remembers the first nonce added for an endpoint and silently discards all future nonces for that endpoint. With my patch `SimpleNonceStore` will remember multiple nonces per endpoint.
For people using the `SimpleNonceStore` in production, this is probably a **medium level security patch** that helps prevent replay attacks.
=> Add SimpleNonceStore the ability to store multiple nonces per endpoint

verify.go, verify_test.go
Currently nonces are verified in a universal set for all endpoints. This is unnecessarily strict and can cause false negatives. That is, currently completely valid auth attempts can fail verification if another endpoint has used the same nonce.
This was reported in #11 and thus this patch resolves that issue.
=> Do nonce verification per endpoint. Fixes #11.

xrds.go, xrds_test.go
The [OpenID 2.0 spec point 7.3.2.2](http://openid.net/specs/openid-authentication-2_0.html#discovery) states that "*... MUST first search the document [...] for an OP Identifier Element. If none is found, the RP will search for a Claimed Identifier Element.*"
Currently the code uses whichever one of those two comes first in the XRD. This patch implements the correct search order.
=> OP Identifier Element has priority over Claimed Identifier Element.

verify.go
The [OpenID 2.0 spec point 11.2](http://openid.net/specs/openid-authentication-2_0.html#verify_disco) states that "*... the "openid.identity" in the request was "http://specs.openid.net/auth/2.0/identifier_select" ...*"
Currently the code compares that URL against `openid.claimed_id`. This patch implements the correct comparsion against `openid.identity`.
=> Correctly check openid.identity when verifying discovered information

_example/login.html
The [OpenID 2.0 spec point 7.1](http://openid.net/specs/openid-authentication-2_0.html#initiation) states that "*The form field's "name" attribute SHOULD have the value "openid_identifier", so that User-Agents can automatically determine that this is an OpenID form*"
My patch implements this recommended attribute in the example.
=> Add a detectable name attribute to the identifier field in the example

discover.go, discover_test.go
The [OpenID 2.0 spec point 7.2](http://openid.net/specs/openid-authentication-2_0.html#normalization) states that "*The end user's input MUST be normalized into an Identifier ...*"
The current code does contain a function that does the normalizing, however it isn't used anywhere, not even in the example. This patch adds normalization to the start of discovery to meet the spec requirement.
=> Normalize the Identifier before discovery.

_example/login.html, _example/server.go, integration/discovery_test.go
[Steam](https://en.wikipedia.org/wiki/Steam_(software)) seems to be one of the last major OpenID 2.0 providers with absolutely no alternative auth method publicly planned. Thus I expect a good chunk of new users of this library to use it for Steam.
There's some anecdotal evidence of this in issue #11, in [random reddit threads](https://www.reddit.com/r/golang/comments/36lf6o/golang_and_openid/) mentioning using this library with Steam, and I myself am planning on using it exclusively for Steam.
This patch introduces some Steam specific additions.
1) A real-world discover test.
2) A predefined button in the example.
3) A defined realm in the example. Steam makes this a mandatory parameter. Having it in the example will make life easier for Steam users, while having no negative effect on …
=> Steam specific additions

_example/login.html
As mentioned in #16 - Google has [stopped supporting OpenID 2.0](https://developers.google.com/identity/protocols/OpenID2Migration?hl=en).
This patch removes the now defunct button from the example page.
=> Remove the defunct Google button from the example

verify.go, verify_test.go
The [OpenID 2.0 spec point 10.1](http://openid.net/specs/openid-authentication-2_0.html#positive_assertions) states that "*[openid.signed] MUST contain at least "op_endpoint", "return_to" "response_nonce" and "assoc_handle", and if present in the response, "claimed_id" and "identity".*"
Currently the code doesn't verify any of this. This patch implements this verification.
This is a **high level security vulnerability**.
One attack scenario being where the attacker acquires a legitimate positive assertion without the `claimed_id` field. Then intercepting the browser redirect to the callback and adding their own malicious `claimed_id` field. All verifications pass and the malicious `claimed_id` is treated as verified.
I wrote a crude proof of concept exploit for this and tested it on the …
=> Properly check if all the required fields have been signed

verify.go
This patch moves the signature verification step to an earlier time. This was also discussed briefly in #26.
Currently `verifySignature` is called after `verifyNonce`, which means that the nonce store can be polluted with garbage that doesn't have a verified signature. Doing `verifyNonce` as the last step is a simple solution to this problem.
The [OpenID 2.0 spec point 11](http://openid.net/specs/openid-authentication-2_0.html#verification), which covers verification, doesn't demand any specific order of these verification sub-steps. These steps are all additive, so changing the order to suit our implementation specific needs is perfectly valid.
=> Do signature verification earlier

_example/server.go, discovery_cache.go, discovery_cache_test.go
The `SimpleDiscoveryCache` has the same synchronization requirements as `SimpleNonceStore`. I have now solved it the same way as it has been solved for the nonce store, with mutexes guarding the map.
I also added a new convenience function `NewSimpleDiscoveryCache`, similarly to the nonce store, for easy instance creation.
=> Add synchronization to the simple discovery cache

_example/server.go, nonce_store.go, nonce_store_test.go, verify_test.go
This patch is about making the simple nonce store more resilient against failure.
1) Added a new `NewSimpleNonceStore` function that returns `*SimpleNonceStore`.
The `SimpleNonceStore` instance creation is already quite a bit of code. Even more so after this patch and with package prefixes. By having people just call `NewSimpleNonceStore` is idiomatic Go code and gives less room for failure.
2) Changed the `SimpleNonceStore` mutex to a pointer to a mutex.
The example code did everything correctly with the regular mutex, but it's easier to hurt oneself with a regular mutex here when writing new code. If a user would pass around a `SimpleNonceStore` instead of `*SimpleNonceStore`, everything would compile and even run! A copy of a `SimpleNonceStore` instance still satisfies the `NonceStore` …
=> Make simple nonce store more foolproof

integration/discovery_test.go
This patch would make it easier to develop & test this library in folders other than `github.com/yohcop/openid-go`. For example I do development in my own unstable branches that aren't even located in GOPATH. The integration tests still point towards the master yohcop branch. This patch makes the import relative, allowing it to work in all sorts of configurations.
=> Use a relative import path for integration tests

redirect.go, redirect_test.go
The authentication request wasn't being built according to the spec. It managed to still somewhat work mostly due to implementation quirks in other parts of the library.
The [OpenID 2.0 spec point 7.3.1](http://openid.net/specs/openid-authentication-2_0.html#discovery) states that *"http://specs.openid.net/auth/2.0/identifier_select" MUST be used as both the Claimed Identifier and the OP-Local Identifier when an OP Identifier is entered*. Previously only the local id was being set to this URL in such a case. (Due to implementation quirks, this code path is actually dead. I will address this in a future pull request.)
The [OpenID 2.0 spec point 9.1](http://openid.net/specs/openid-authentication-2_0.html#anchor27) states that *If a different OP-Local Identifier is not specified, the claimed …
=> Fix authentication request parameter building

discover.go, discover_test.go, integration/discovery_test.go
The [OpenID 2.0 spec point 7.3.1](http://openid.net/specs/openid-authentication-2_0.html#discovery) states that *For the purposes of making OpenID Authentication requests, the value "http://specs.openid.net/auth/2.0/identifier_select" MUST be used as both the Claimed Identifier and the OP-Local Identifier when an OP Identifier is entered*.
This authentication request is being built in the `buildRedirectURL` function in the `redirect.go` file. The `identifier_select` URL is assigned there as needed. The `discover` function does not need to return this.
=> Don't override discovered ids with identifier_select URLs

redirect.go, redirect_test.go
I have a situation where I need to support only already-known OP endpoints, so I can skip the discovery part of building the redirect URL.
This patch exposes the `BuildRedirectURL` function to facilitate this.
=> Expose the BuildRedirectURL function

README.md, discover.go, discover_test.go, fake_getter_test.go, getter.go, openid.go, redirect.go, redirect_test.go, verify.go, verify_test.go
Unfortunately not every Go runtime environment has a functional `http.DefaultClient`, which is used by this library to do all the HTTP requests.
One such environment is [Google App Engine](https://en.wikipedia.org/wiki/Google_App_Engine). In addition to needing to use a custom `http.Client`, this custom client is also different on a per-request basis, so just exposing `urlGetter` isn't going to cut it.
My patch adds the ability to provide a custom `http.Client` on a per-instance basis, which is sufficient to fully support App Engine. The existing static functions now use a default instance under the hood.
=> Making http.Client configurable on a per-instance basis

html_discovery.go, html_discovery_test.go
These are found in the wild (like in my own openid)
If you want to test: https://strk.kbt.io/openid/
=> Support openid2.provider in self-closing tags

normalizer.go, normalizer_test.go
Both [OpenID 2.0 spec point 7.2](http://openid.net/specs/openid-authentication-2_0.html#normalization) and [XRI 2.0 spec point 2.2.2](https://www.oasis-open.org/committees/download.php/15376#_Toc117301850) mention the cross-reference mechanism of XRI where the URI starts with an open parenthesis. Indeed this was even mentioned in the pasted spec text that was above the affected code line.
This PR fixes the omission and adds a test for it.
=> Fix XRI Cross-Reference URI detection

integration/discovery_test.go
I originally changed this to relative import with #36 in order to easily test without using GOPATH.
Relative imports in Go are a peculiar thing. They aren't advertised as even existing and are a historical quirk that predates the concept of GOPATH. There have been [suggestions to ban](https://github.com/golang/go/issues/6147) the usage of them, although that ended with *we should keep the limited support* and [there are tests for it](https://golang.org/src/cmd/go/testdata/local/easysub/main.go) working in the Go compiler.
In practice it kept working for me until today when it suddenly stopped. Now I get linker errors, similar to what was [reported here](https://github.com/golang/go/issues/14683).
Because relative imports aren't properly supported and have seemingly random linker errors at …
=> Revert back to explicit import in the integration test

.travis.yml, go.mod, go.sum, nonce_store.go
This PR adds the `go.mod` and `go.sum` files needed to define dependencies in the new [Go modules system](https://github.com/golang/go/wiki/Modules).
I'm not very familiar with Travis, but I updated the config file based on some quick reading of [their documentation](https://docs.travis-ci.com/user/languages/go/). Hopefully it works.
Go 1.11 was complaining about `Errorf format %d has arg diff.Seconds() of wrong type float64`. I checked the Go 1.3 stdlib source and it was always `float64`. I guess the warning is new. In any case, I fixed the issue.
After this has been merged, please [tag the latest commit with semver](https://github.com/golang/go/wiki/Modules#modules). `v1.0.0` sounds good to me.
=> Add Go modules support.

yadis_discovery.go
Some identity provider websites use XHTML doctype which enforces the use of /> even for meta tags. This is not recognized by this program and lead to the site not being recognized/discovered and errors are thrown,
This PR is a re-submission of #52 .
=> Fix discovery of self-closing X-XRDS-Location meta tag
